"""add_boq_module

Revision ID: 316d0b4fecb9
Revises: 465eded9f763
Create Date: 2026-05-01 01:15:29.325885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '316d0b4fecb9'
down_revision: Union[str, None] = '465eded9f763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    sa.Enum(
        'CIVIL',
        'STRUCTURAL',
        'ARCHITECTURAL',
        'MEP',
        'FINISHING',
        'EXTERNAL',
        'PRELIMINARY',
        'OTHER',
        name='costcodecategory',
    ).create(bind, checkfirst=True)
    sa.Enum(
        'SQM',
        'CUM',
        'RMT',
        'NOS',
        'KG',
        'MT',
        'LIT',
        'BAG',
        'LS',
        'DAY',
        'HOUR',
        'PERCENT',
        name='unitofmeasure',
    ).create(bind, checkfirst=True)
    sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'SUPERSEDED', name='budgetversionstatus').create(
        bind, checkfirst=True
    )
    sa.Enum('DRAFT', 'APPROVED', 'REVISED', 'LOCKED', name='boqitemstatus').create(bind, checkfirst=True)
    sa.Enum('MATERIAL', 'LABOUR', 'EQUIPMENT', name='ratecomponenttype').create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_codes',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('CIVIL', 'STRUCTURAL', 'ARCHITECTURAL', 'MEP', 'FINISHING', 'EXTERNAL', 'PRELIMINARY', 'OTHER', name='costcodecategory', create_type=False), nullable=False),
    sa.Column('unit', sa.Enum('SQM', 'CUM', 'RMT', 'NOS', 'KG', 'MT', 'LIT', 'BAG', 'LS', 'DAY', 'HOUR', 'PERCENT', name='unitofmeasure', create_type=False), nullable=False),
    sa.Column('standard_rate', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_codes_tenant_id'), 'cost_codes', ['tenant_id'], unique=False)
    op.create_table('budget_versions',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'SUPERSEDED', name='budgetversionstatus', create_type=False), nullable=False),
    sa.Column('total_material_cost', sa.Float(), nullable=False),
    sa.Column('total_labour_cost', sa.Float(), nullable=False),
    sa.Column('total_equipment_cost', sa.Float(), nullable=False),
    sa.Column('total_overhead', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('contingency_percentage', sa.Float(), nullable=False),
    sa.Column('contingency_amount', sa.Float(), nullable=False),
    sa.Column('grand_total', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_versions_project_id'), 'budget_versions', ['project_id'], unique=False)
    op.create_index(op.f('ix_budget_versions_tenant_id'), 'budget_versions', ['tenant_id'], unique=False)
    op.create_table('rate_analyses',
    sa.Column('cost_code_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.Enum('SQM', 'CUM', 'RMT', 'NOS', 'KG', 'MT', 'LIT', 'BAG', 'LS', 'DAY', 'HOUR', 'PERCENT', name='unitofmeasure', create_type=False), nullable=False),
    sa.Column('output_quantity', sa.Float(), nullable=False),
    sa.Column('total_material', sa.Float(), nullable=False),
    sa.Column('total_labour', sa.Float(), nullable=False),
    sa.Column('total_equipment', sa.Float(), nullable=False),
    sa.Column('overhead_percentage', sa.Float(), nullable=False),
    sa.Column('overhead_amount', sa.Float(), nullable=False),
    sa.Column('unit_rate', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cost_code_id'], ['cost_codes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_analyses_cost_code_id'), 'rate_analyses', ['cost_code_id'], unique=False)
    op.create_index(op.f('ix_rate_analyses_tenant_id'), 'rate_analyses', ['tenant_id'], unique=False)
    op.create_table('boq_items',
    sa.Column('budget_version_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('cost_code_id', sa.String(length=36), nullable=True),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('item_number', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('specification', sa.Text(), nullable=True),
    sa.Column('unit', sa.Enum('SQM', 'CUM', 'RMT', 'NOS', 'KG', 'MT', 'LIT', 'BAG', 'LS', 'DAY', 'HOUR', 'PERCENT', name='unitofmeasure', create_type=False), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_rate', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('material_rate', sa.Float(), nullable=False),
    sa.Column('labour_rate', sa.Float(), nullable=False),
    sa.Column('equipment_rate', sa.Float(), nullable=False),
    sa.Column('overhead_rate', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'REVISED', 'LOCKED', name='boqitemstatus', create_type=False), nullable=False),
    sa.Column('is_section_header', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('actual_quantity', sa.Float(), nullable=False),
    sa.Column('actual_amount', sa.Float(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['budget_version_id'], ['budget_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cost_code_id'], ['cost_codes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['boq_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boq_items_budget_version_id'), 'boq_items', ['budget_version_id'], unique=False)
    op.create_index(op.f('ix_boq_items_cost_code_id'), 'boq_items', ['cost_code_id'], unique=False)
    op.create_index(op.f('ix_boq_items_project_id'), 'boq_items', ['project_id'], unique=False)
    op.create_index(op.f('ix_boq_items_tenant_id'), 'boq_items', ['tenant_id'], unique=False)
    op.create_table('rate_analysis_components',
    sa.Column('rate_analysis_id', sa.String(length=36), nullable=False),
    sa.Column('component_type', sa.Enum('MATERIAL', 'LABOUR', 'EQUIPMENT', name='ratecomponenttype', create_type=False), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.Enum('SQM', 'CUM', 'RMT', 'NOS', 'KG', 'MT', 'LIT', 'BAG', 'LS', 'DAY', 'HOUR', 'PERCENT', name='unitofmeasure', create_type=False), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('wastage_percentage', sa.Float(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rate_analysis_id'], ['rate_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_analysis_components_rate_analysis_id'), 'rate_analysis_components', ['rate_analysis_id'], unique=False)
    op.create_index(op.f('ix_rate_analysis_components_tenant_id'), 'rate_analysis_components', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    op.drop_index(op.f('ix_rate_analysis_components_tenant_id'), table_name='rate_analysis_components')
    op.drop_index(op.f('ix_rate_analysis_components_rate_analysis_id'), table_name='rate_analysis_components')
    op.drop_table('rate_analysis_components')
    op.drop_index(op.f('ix_boq_items_tenant_id'), table_name='boq_items')
    op.drop_index(op.f('ix_boq_items_project_id'), table_name='boq_items')
    op.drop_index(op.f('ix_boq_items_cost_code_id'), table_name='boq_items')
    op.drop_index(op.f('ix_boq_items_budget_version_id'), table_name='boq_items')
    op.drop_table('boq_items')
    op.drop_index(op.f('ix_rate_analyses_tenant_id'), table_name='rate_analyses')
    op.drop_index(op.f('ix_rate_analyses_cost_code_id'), table_name='rate_analyses')
    op.drop_table('rate_analyses')
    op.drop_index(op.f('ix_budget_versions_tenant_id'), table_name='budget_versions')
    op.drop_index(op.f('ix_budget_versions_project_id'), table_name='budget_versions')
    op.drop_table('budget_versions')
    op.drop_index(op.f('ix_cost_codes_tenant_id'), table_name='cost_codes')
    op.drop_table('cost_codes')
    sa.Enum('MATERIAL', 'LABOUR', 'EQUIPMENT', name='ratecomponenttype').drop(bind, checkfirst=True)
    sa.Enum('DRAFT', 'APPROVED', 'REVISED', 'LOCKED', name='boqitemstatus').drop(bind, checkfirst=True)
    sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'SUPERSEDED', name='budgetversionstatus').drop(bind, checkfirst=True)
    sa.Enum(
        'SQM',
        'CUM',
        'RMT',
        'NOS',
        'KG',
        'MT',
        'LIT',
        'BAG',
        'LS',
        'DAY',
        'HOUR',
        'PERCENT',
        name='unitofmeasure',
    ).drop(bind, checkfirst=True)
    sa.Enum(
        'CIVIL',
        'STRUCTURAL',
        'ARCHITECTURAL',
        'MEP',
        'FINISHING',
        'EXTERNAL',
        'PRELIMINARY',
        'OTHER',
        name='costcodecategory',
    ).drop(bind, checkfirst=True)
    # ### end Alembic commands ###
