"""add_procurement

Revision ID: 39a6cfeaa1bc
Revises: 316d0b4fecb9
Create Date: 2026-05-01 15:05:09.428916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39a6cfeaa1bc'
down_revision: Union[str, None] = '316d0b4fecb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    sa.Enum(
        'MATERIAL_SUPPLIER',
        'SUBCONTRACTOR',
        'EQUIPMENT_RENTAL',
        'CONSULTANT',
        'OTHER',
        name='vendorcategory',
    ).create(bind, checkfirst=True)
    sa.Enum('ACTIVE', 'INACTIVE', 'BLACKLISTED', name='vendorstatus').create(bind, checkfirst=True)
    sa.Enum('DRAFT', 'SENT', 'CLOSED', 'CANCELLED', name='rfqstatus').create(bind, checkfirst=True)
    sa.Enum('RECEIVED', 'UNDER_REVIEW', 'ACCEPTED', 'REJECTED', name='quotationstatus').create(
        bind, checkfirst=True
    )
    sa.Enum(
        'DRAFT',
        'PENDING_APPROVAL',
        'APPROVED',
        'SENT',
        'PARTIALLY_RECEIVED',
        'FULLY_RECEIVED',
        'CANCELLED',
        name='postatus',
    ).create(bind, checkfirst=True)
    sa.Enum('DRAFT', 'CONFIRMED', 'REJECTED', name='grnstatus').create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('category', sa.Enum('MATERIAL_SUPPLIER', 'SUBCONTRACTOR', 'EQUIPMENT_RENTAL', 'CONSULTANT', 'OTHER', name='vendorcategory', create_type=False), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BLACKLISTED', name='vendorstatus', create_type=False), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('pan_number', sa.String(length=20), nullable=True),
    sa.Column('vat_number', sa.String(length=20), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('bank_account', sa.String(length=50), nullable=True),
    sa.Column('credit_days', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_tenant_id'), 'vendors', ['tenant_id'], unique=False)
    op.create_table('rfqs',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('rfq_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'CLOSED', 'CANCELLED', name='rfqstatus', create_type=False), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('terms_conditions', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfqs_project_id'), 'rfqs', ['project_id'], unique=False)
    op.create_index(op.f('ix_rfqs_tenant_id'), 'rfqs', ['tenant_id'], unique=False)
    op.create_table('quotations',
    sa.Column('rfq_id', sa.String(length=36), nullable=False),
    sa.Column('vendor_id', sa.String(length=36), nullable=False),
    sa.Column('quotation_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'UNDER_REVIEW', 'ACCEPTED', 'REJECTED', name='quotationstatus', create_type=False), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('delivery_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotations_rfq_id'), 'quotations', ['rfq_id'], unique=False)
    op.create_index(op.f('ix_quotations_tenant_id'), 'quotations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_quotations_vendor_id'), 'quotations', ['vendor_id'], unique=False)
    op.create_table('rfq_items',
    sa.Column('rfq_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('specification', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfq_items_rfq_id'), 'rfq_items', ['rfq_id'], unique=False)
    op.create_index(op.f('ix_rfq_items_tenant_id'), 'rfq_items', ['tenant_id'], unique=False)
    op.create_table('rfq_vendors',
    sa.Column('rfq_id', sa.String(length=36), nullable=False),
    sa.Column('vendor_id', sa.String(length=36), nullable=False),
    sa.Column('sent_at', sa.Date(), nullable=True),
    sa.Column('responded', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfq_vendors_rfq_id'), 'rfq_vendors', ['rfq_id'], unique=False)
    op.create_index(op.f('ix_rfq_vendors_tenant_id'), 'rfq_vendors', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_rfq_vendors_vendor_id'), 'rfq_vendors', ['vendor_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('vendor_id', sa.String(length=36), nullable=False),
    sa.Column('quotation_id', sa.String(length=36), nullable=True),
    sa.Column('po_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'SENT', 'PARTIALLY_RECEIVED', 'FULLY_RECEIVED', 'CANCELLED', name='postatus', create_type=False), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('payment_terms', sa.String(length=255), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('grand_total', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_project_id'), 'purchase_orders', ['project_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_tenant_id'), 'purchase_orders', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_vendor_id'), 'purchase_orders', ['vendor_id'], unique=False)
    op.create_table('quotation_items',
    sa.Column('quotation_id', sa.String(length=36), nullable=False),
    sa.Column('rfq_item_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_rate', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rfq_item_id'], ['rfq_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_items_quotation_id'), 'quotation_items', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_quotation_items_tenant_id'), 'quotation_items', ['tenant_id'], unique=False)
    op.create_table('grns',
    sa.Column('po_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('grn_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'REJECTED', name='grnstatus', create_type=False), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('received_by', sa.String(length=36), nullable=True),
    sa.Column('delivery_note', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('inspection_passed', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grns_po_id'), 'grns', ['po_id'], unique=False)
    op.create_index(op.f('ix_grns_project_id'), 'grns', ['project_id'], unique=False)
    op.create_index(op.f('ix_grns_tenant_id'), 'grns', ['tenant_id'], unique=False)
    op.create_table('po_items',
    sa.Column('po_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_rate', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('received_quantity', sa.Float(), nullable=False),
    sa.Column('boq_item_id', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_po_items_po_id'), 'po_items', ['po_id'], unique=False)
    op.create_index(op.f('ix_po_items_tenant_id'), 'po_items', ['tenant_id'], unique=False)
    op.create_table('grn_items',
    sa.Column('grn_id', sa.String(length=36), nullable=False),
    sa.Column('po_item_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('ordered_quantity', sa.Float(), nullable=False),
    sa.Column('received_quantity', sa.Float(), nullable=False),
    sa.Column('rejected_quantity', sa.Float(), nullable=False),
    sa.Column('unit_rate', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['grn_id'], ['grns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['po_item_id'], ['po_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grn_items_grn_id'), 'grn_items', ['grn_id'], unique=False)
    op.create_index(op.f('ix_grn_items_tenant_id'), 'grn_items', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    op.drop_index(op.f('ix_grn_items_tenant_id'), table_name='grn_items')
    op.drop_index(op.f('ix_grn_items_grn_id'), table_name='grn_items')
    op.drop_table('grn_items')
    op.drop_index(op.f('ix_po_items_tenant_id'), table_name='po_items')
    op.drop_index(op.f('ix_po_items_po_id'), table_name='po_items')
    op.drop_table('po_items')
    op.drop_index(op.f('ix_grns_tenant_id'), table_name='grns')
    op.drop_index(op.f('ix_grns_project_id'), table_name='grns')
    op.drop_index(op.f('ix_grns_po_id'), table_name='grns')
    op.drop_table('grns')
    op.drop_index(op.f('ix_quotation_items_tenant_id'), table_name='quotation_items')
    op.drop_index(op.f('ix_quotation_items_quotation_id'), table_name='quotation_items')
    op.drop_table('quotation_items')
    op.drop_index(op.f('ix_purchase_orders_vendor_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_tenant_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_project_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_rfq_vendors_vendor_id'), table_name='rfq_vendors')
    op.drop_index(op.f('ix_rfq_vendors_tenant_id'), table_name='rfq_vendors')
    op.drop_index(op.f('ix_rfq_vendors_rfq_id'), table_name='rfq_vendors')
    op.drop_table('rfq_vendors')
    op.drop_index(op.f('ix_rfq_items_tenant_id'), table_name='rfq_items')
    op.drop_index(op.f('ix_rfq_items_rfq_id'), table_name='rfq_items')
    op.drop_table('rfq_items')
    op.drop_index(op.f('ix_quotations_vendor_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_tenant_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_rfq_id'), table_name='quotations')
    op.drop_table('quotations')
    op.drop_index(op.f('ix_rfqs_tenant_id'), table_name='rfqs')
    op.drop_index(op.f('ix_rfqs_project_id'), table_name='rfqs')
    op.drop_table('rfqs')
    op.drop_index(op.f('ix_vendors_tenant_id'), table_name='vendors')
    op.drop_table('vendors')
    sa.Enum('DRAFT', 'CONFIRMED', 'REJECTED', name='grnstatus').drop(bind, checkfirst=True)
    sa.Enum(
        'DRAFT',
        'PENDING_APPROVAL',
        'APPROVED',
        'SENT',
        'PARTIALLY_RECEIVED',
        'FULLY_RECEIVED',
        'CANCELLED',
        name='postatus',
    ).drop(bind, checkfirst=True)
    sa.Enum('RECEIVED', 'UNDER_REVIEW', 'ACCEPTED', 'REJECTED', name='quotationstatus').drop(
        bind, checkfirst=True
    )
    sa.Enum('DRAFT', 'SENT', 'CLOSED', 'CANCELLED', name='rfqstatus').drop(bind, checkfirst=True)
    sa.Enum('ACTIVE', 'INACTIVE', 'BLACKLISTED', name='vendorstatus').drop(bind, checkfirst=True)
    sa.Enum(
        'MATERIAL_SUPPLIER',
        'SUBCONTRACTOR',
        'EQUIPMENT_RENTAL',
        'CONSULTANT',
        'OTHER',
        name='vendorcategory',
    ).drop(bind, checkfirst=True)
    # ### end Alembic commands ###
