"""add_user_permissions_must_change_password

Revision ID: 3b7b16177ea1
Revises: 14b1106bef26
Create Date: 2026-06-07 07:57:01.430300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b7b16177ea1'
down_revision: Union[str, None] = '14b1106bef26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_permissions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('can_projects', sa.Boolean(), nullable=False),
    sa.Column('can_boq', sa.Boolean(), nullable=False),
    sa.Column('can_procurement', sa.Boolean(), nullable=False),
    sa.Column('can_inventory', sa.Boolean(), nullable=False),
    sa.Column('can_site_ops', sa.Boolean(), nullable=False),
    sa.Column('can_finance', sa.Boolean(), nullable=False),
    sa.Column('can_quality', sa.Boolean(), nullable=False),
    sa.Column('can_documents', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_permissions_tenant_id'), 'user_permissions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_permissions_user_id'), 'user_permissions', ['user_id'], unique=False)
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default=sa.false(),))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'must_change_password')
    op.drop_index(op.f('ix_user_permissions_user_id'), table_name='user_permissions')
    op.drop_index(op.f('ix_user_permissions_tenant_id'), table_name='user_permissions')
    op.drop_table('user_permissions')
    # ### end Alembic commands ###
