"""add_procurement_inventory

Revision ID: 4da8913e3093
Revises: 39a6cfeaa1bc
Create Date: 2026-05-01 15:29:05.972260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4da8913e3093'
down_revision: Union[str, None] = '39a6cfeaa1bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_codes',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('CIVIL', 'STRUCTURAL', 'ARCHITECTURAL', 'MEP', 'FINISHING', 'EXTERNAL', 'PRELIMINARY', 'OTHER', name='costcodecategory'), nullable=False),
    sa.Column('unit', sa.Enum('SQM', 'CUM', 'RMT', 'NOS', 'KG', 'MT', 'LIT', 'BAG', 'LS', 'DAY', 'HOUR', 'PERCENT', name='unitofmeasure'), nullable=False),
    sa.Column('standard_rate', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_codes_tenant_id'), 'cost_codes', ['tenant_id'], unique=False)
    op.create_table('budget_versions',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'SUPERSEDED', name='budgetversionstatus'), nullable=False),
    sa.Column('total_material_cost', sa.Float(), nullable=False),
    sa.Column('total_labour_cost', sa.Float(), nullable=False),
    sa.Column('total_equipment_cost', sa.Float(), nullable=False),
    sa.Column('total_overhead', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('contingency_percentage', sa.Float(), nullable=False),
    sa.Column('contingency_amount', sa.Float(), nullable=False),
    sa.Column('grand_total', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_versions_project_id'), 'budget_versions', ['project_id'], unique=False)
    op.create_index(op.f('ix_budget_versions_tenant_id'), 'budget_versions', ['tenant_id'], unique=False)
    op.create_table('rate_analyses',
    sa.Column('cost_code_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.Enum('SQM', 'CUM', 'RMT', 'NOS', 'KG', 'MT', 'LIT', 'BAG', 'LS', 'DAY', 'HOUR', 'PERCENT', name='unitofmeasure'), nullable=False),
    sa.Column('output_quantity', sa.Float(), nullable=False),
    sa.Column('total_material', sa.Float(), nullable=False),
    sa.Column('total_labour', sa.Float(), nullable=False),
    sa.Column('total_equipment', sa.Float(), nullable=False),
    sa.Column('overhead_percentage', sa.Float(), nullable=False),
    sa.Column('overhead_amount', sa.Float(), nullable=False),
    sa.Column('unit_rate', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cost_code_id'], ['cost_codes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_analyses_cost_code_id'), 'rate_analyses', ['cost_code_id'], unique=False)
    op.create_index(op.f('ix_rate_analyses_tenant_id'), 'rate_analyses', ['tenant_id'], unique=False)
    op.create_table('boq_items',
    sa.Column('budget_version_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('cost_code_id', sa.String(length=36), nullable=True),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('item_number', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('specification', sa.Text(), nullable=True),
    sa.Column('unit', sa.Enum('SQM', 'CUM', 'RMT', 'NOS', 'KG', 'MT', 'LIT', 'BAG', 'LS', 'DAY', 'HOUR', 'PERCENT', name='unitofmeasure'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_rate', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('material_rate', sa.Float(), nullable=False),
    sa.Column('labour_rate', sa.Float(), nullable=False),
    sa.Column('equipment_rate', sa.Float(), nullable=False),
    sa.Column('overhead_rate', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'REVISED', 'LOCKED', name='boqitemstatus'), nullable=False),
    sa.Column('is_section_header', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('actual_quantity', sa.Float(), nullable=False),
    sa.Column('actual_amount', sa.Float(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['budget_version_id'], ['budget_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cost_code_id'], ['cost_codes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['boq_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boq_items_budget_version_id'), 'boq_items', ['budget_version_id'], unique=False)
    op.create_index(op.f('ix_boq_items_cost_code_id'), 'boq_items', ['cost_code_id'], unique=False)
    op.create_index(op.f('ix_boq_items_project_id'), 'boq_items', ['project_id'], unique=False)
    op.create_index(op.f('ix_boq_items_tenant_id'), 'boq_items', ['tenant_id'], unique=False)
    op.create_table('rate_analysis_components',
    sa.Column('rate_analysis_id', sa.String(length=36), nullable=False),
    sa.Column('component_type', sa.Enum('MATERIAL', 'LABOUR', 'EQUIPMENT', name='ratecomponenttype'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.Enum('SQM', 'CUM', 'RMT', 'NOS', 'KG', 'MT', 'LIT', 'BAG', 'LS', 'DAY', 'HOUR', 'PERCENT', name='unitofmeasure'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('wastage_percentage', sa.Float(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rate_analysis_id'], ['rate_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_analysis_components_rate_analysis_id'), 'rate_analysis_components', ['rate_analysis_id'], unique=False)
    op.create_index(op.f('ix_rate_analysis_components_tenant_id'), 'rate_analysis_components', ['tenant_id'], unique=False)
    op.create_table('warehouses',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('site_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='warehousestatus'), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_site_store', sa.Boolean(), nullable=False),
    sa.Column('keeper_id', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_tenant_id'), 'warehouses', ['tenant_id'], unique=False)
    op.create_table('material_requests',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=True),
    sa.Column('from_warehouse_id', sa.String(length=36), nullable=True),
    sa.Column('mr_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'ISSUED', 'REJECTED', name='materialrequeststatus'), nullable=False),
    sa.Column('required_date', sa.String(length=20), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('issued_by', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['warehouses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_requests_project_id'), 'material_requests', ['project_id'], unique=False)
    op.create_index(op.f('ix_material_requests_tenant_id'), 'material_requests', ['tenant_id'], unique=False)
    op.create_table('stock_items',
    sa.Column('warehouse_id', sa.String(length=36), nullable=False),
    sa.Column('material_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('quantity_on_hand', sa.Float(), nullable=False),
    sa.Column('reserved_quantity', sa.Float(), nullable=False),
    sa.Column('reorder_level', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_items_material_code'), 'stock_items', ['material_code'], unique=False)
    op.create_index(op.f('ix_stock_items_tenant_id'), 'stock_items', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_stock_items_warehouse_id'), 'stock_items', ['warehouse_id'], unique=False)
    op.create_table('material_request_items',
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('stock_item_id', sa.String(length=36), nullable=True),
    sa.Column('material_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('requested_quantity', sa.Float(), nullable=False),
    sa.Column('approved_quantity', sa.Float(), nullable=False),
    sa.Column('issued_quantity', sa.Float(), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['material_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_request_items_request_id'), 'material_request_items', ['request_id'], unique=False)
    op.create_index(op.f('ix_material_request_items_tenant_id'), 'material_request_items', ['tenant_id'], unique=False)
    op.create_table('stock_transactions',
    sa.Column('stock_item_id', sa.String(length=36), nullable=False),
    sa.Column('warehouse_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('transaction_type', sa.Enum('RECEIPT', 'ISSUE', 'TRANSFER', 'RETURN', 'ADJUSTMENT', 'CONSUMPTION', name='transactiontype'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('balance_after', sa.Float(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_transactions_stock_item_id'), 'stock_transactions', ['stock_item_id'], unique=False)
    op.create_index(op.f('ix_stock_transactions_tenant_id'), 'stock_transactions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_stock_transactions_warehouse_id'), 'stock_transactions', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_transactions_warehouse_id'), table_name='stock_transactions')
    op.drop_index(op.f('ix_stock_transactions_tenant_id'), table_name='stock_transactions')
    op.drop_index(op.f('ix_stock_transactions_stock_item_id'), table_name='stock_transactions')
    op.drop_table('stock_transactions')
    op.drop_index(op.f('ix_material_request_items_tenant_id'), table_name='material_request_items')
    op.drop_index(op.f('ix_material_request_items_request_id'), table_name='material_request_items')
    op.drop_table('material_request_items')
    op.drop_index(op.f('ix_stock_items_warehouse_id'), table_name='stock_items')
    op.drop_index(op.f('ix_stock_items_tenant_id'), table_name='stock_items')
    op.drop_index(op.f('ix_stock_items_material_code'), table_name='stock_items')
    op.drop_table('stock_items')
    op.drop_index(op.f('ix_material_requests_tenant_id'), table_name='material_requests')
    op.drop_index(op.f('ix_material_requests_project_id'), table_name='material_requests')
    op.drop_table('material_requests')
    op.drop_index(op.f('ix_warehouses_tenant_id'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_rate_analysis_components_tenant_id'), table_name='rate_analysis_components')
    op.drop_index(op.f('ix_rate_analysis_components_rate_analysis_id'), table_name='rate_analysis_components')
    op.drop_table('rate_analysis_components')
    op.drop_index(op.f('ix_boq_items_tenant_id'), table_name='boq_items')
    op.drop_index(op.f('ix_boq_items_project_id'), table_name='boq_items')
    op.drop_index(op.f('ix_boq_items_cost_code_id'), table_name='boq_items')
    op.drop_index(op.f('ix_boq_items_budget_version_id'), table_name='boq_items')
    op.drop_table('boq_items')
    op.drop_index(op.f('ix_rate_analyses_tenant_id'), table_name='rate_analyses')
    op.drop_index(op.f('ix_rate_analyses_cost_code_id'), table_name='rate_analyses')
    op.drop_table('rate_analyses')
    op.drop_index(op.f('ix_budget_versions_tenant_id'), table_name='budget_versions')
    op.drop_index(op.f('ix_budget_versions_project_id'), table_name='budget_versions')
    op.drop_table('budget_versions')
    op.drop_index(op.f('ix_cost_codes_tenant_id'), table_name='cost_codes')
    op.drop_table('cost_codes')
    # ### end Alembic commands ###
