"""add_subcontractors_and_comments

Revision ID: 5d690d8ab628
Revises: 01ceab6d28d6
Create Date: 2026-06-24 22:35:17.072988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d690d8ab628'
down_revision: Union[str, None] = '01ceab6d28d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcontractors',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('specialty', sa.Enum('STRUCTURAL', 'ELECTRICAL', 'PLUMBING', 'HVAC', 'FINISHING', 'ROOFING', 'PAINTING', 'LANDSCAPING', 'GENERAL', 'OTHER', name='subcontractorspecialty'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BLACKLISTED', name='subcontractorstatus'), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('gst_number', sa.String(length=50), nullable=True),
    sa.Column('pan_number', sa.String(length=50), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('insurance_provider', sa.String(length=255), nullable=True),
    sa.Column('insurance_valid_until', sa.Date(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcontractors_tenant_id'), 'subcontractors', ['tenant_id'], unique=False)
    op.create_table('comments',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Polymorphic comments — target_type + target_id form a FK to any entity'
    )
    op.create_index(op.f('ix_comments_author_id'), 'comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_comments_target_id'), 'comments', ['target_id'], unique=False)
    op.create_index(op.f('ix_comments_target_type'), 'comments', ['target_type'], unique=False)
    op.create_table('subcontractor_contracts',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('subcontractor_id', sa.String(length=36), nullable=False),
    sa.Column('contract_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'TERMINATED', 'CANCELLED', name='contractstatus'), nullable=False),
    sa.Column('scope_of_work', sa.Text(), nullable=True),
    sa.Column('contract_value', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('retention_percentage', sa.Float(), nullable=False),
    sa.Column('signed_date', sa.Date(), nullable=True),
    sa.Column('signed_by', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subcontractor_id'], ['subcontractors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcontractor_contracts_project_id'), 'subcontractor_contracts', ['project_id'], unique=False)
    op.create_index(op.f('ix_subcontractor_contracts_subcontractor_id'), 'subcontractor_contracts', ['subcontractor_id'], unique=False)
    op.create_index(op.f('ix_subcontractor_contracts_tenant_id'), 'subcontractor_contracts', ['tenant_id'], unique=False)
    op.create_table('work_orders',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('work_order_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='workorderstatus'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('scheduled_start', sa.Date(), nullable=True),
    sa.Column('scheduled_end', sa.Date(), nullable=True),
    sa.Column('actual_start', sa.Date(), nullable=True),
    sa.Column('actual_end', sa.Date(), nullable=True),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['subcontractor_contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_orders_contract_id'), 'work_orders', ['contract_id'], unique=False)
    op.create_index(op.f('ix_work_orders_project_id'), 'work_orders', ['project_id'], unique=False)
    op.create_index(op.f('ix_work_orders_tenant_id'), 'work_orders', ['tenant_id'], unique=False)
    op.drop_index('ix_device_tokens_tenant_id', table_name='device_tokens')
    op.drop_index('ix_device_tokens_user_id', table_name='device_tokens')
    op.drop_index('ix_device_tokens_user_token', table_name='device_tokens')
    op.drop_table('device_tokens')
    op.add_column(
        'user_permissions',
        sa.Column(
            'can_subcontractors',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.alter_column(
        'user_permissions',
        'can_subcontractors',
        server_default=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_permissions', 'can_subcontractors')
    op.create_table('device_tokens',
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='device_tokens_pkey')
    )
    op.create_index('ix_device_tokens_user_token', 'device_tokens', ['user_id', 'token'], unique=True)
    op.create_index('ix_device_tokens_user_id', 'device_tokens', ['user_id'], unique=False)
    op.create_index('ix_device_tokens_tenant_id', 'device_tokens', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_work_orders_tenant_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_project_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_contract_id'), table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_subcontractor_contracts_tenant_id'), table_name='subcontractor_contracts')
    op.drop_index(op.f('ix_subcontractor_contracts_subcontractor_id'), table_name='subcontractor_contracts')
    op.drop_index(op.f('ix_subcontractor_contracts_project_id'), table_name='subcontractor_contracts')
    op.drop_table('subcontractor_contracts')
    op.drop_index(op.f('ix_comments_target_type'), table_name='comments')
    op.drop_index(op.f('ix_comments_target_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_subcontractors_tenant_id'), table_name='subcontractors')
    op.drop_table('subcontractors')
    # ### end Alembic commands ###
