"""add_quality_safety_module

Revision ID: 639ef5cc9db3
Revises: aaa10780aa19
Create Date: 2026-05-10 11:19:12.393387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '639ef5cc9db3'
down_revision: Union[str, None] = 'aaa10780aa19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
