"""add_user_permissions_must_change_password

Revision ID: 6b599b0e7fc9
Revises: 3b7b16177ea1
Create Date: 2026-06-07 09:19:43.513561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b599b0e7fc9'
down_revision: Union[str, None] = '3b7b16177ea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
