"""add_secondary_color_to_tenant

Revision ID: 91a494b510fb
Revises: 6b599b0e7fc9
Create Date: 2026-06-09 00:38:10.654807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91a494b510fb'
down_revision: Union[str, None] = '6b599b0e7fc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('secondary_color', sa.String(length=7), nullable=True))
    op.alter_column('tenants', 'logo_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'logo_url',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('tenants', 'secondary_color')
    # ### end Alembic commands ###
