"""site_ops

Revision ID: e5d30733072f
Revises: 4da8913e3093
Create Date: 2026-05-01 15:38:59.521164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5d30733072f'
down_revision: Union[str, None] = '4da8913e3093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_progress_reports',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('weather', sa.Enum('SUNNY', 'CLOUDY', 'RAINY', 'FOGGY', 'STORMY', name='weathercondition'), nullable=False),
    sa.Column('temperature_celsius', sa.Float(), nullable=True),
    sa.Column('work_hours', sa.Float(), nullable=False),
    sa.Column('is_submitted', sa.Boolean(), nullable=False),
    sa.Column('submitted_by', sa.String(length=36), nullable=True),
    sa.Column('general_notes', sa.Text(), nullable=True),
    sa.Column('safety_notes', sa.Text(), nullable=True),
    sa.Column('total_workers', sa.Integer(), nullable=False),
    sa.Column('total_labour_cost', sa.Float(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_progress_reports_project_id'), 'daily_progress_reports', ['project_id'], unique=False)
    op.create_index(op.f('ix_daily_progress_reports_site_id'), 'daily_progress_reports', ['site_id'], unique=False)
    op.create_index(op.f('ix_daily_progress_reports_tenant_id'), 'daily_progress_reports', ['tenant_id'], unique=False)
    op.create_table('dpr_work_items',
    sa.Column('dpr_id', sa.String(length=36), nullable=False),
    sa.Column('boq_item_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('planned_quantity', sa.Float(), nullable=False),
    sa.Column('achieved_quantity', sa.Float(), nullable=False),
    sa.Column('cumulative_quantity', sa.Float(), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dpr_id'], ['daily_progress_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dpr_work_items_dpr_id'), 'dpr_work_items', ['dpr_id'], unique=False)
    op.create_index(op.f('ix_dpr_work_items_tenant_id'), 'dpr_work_items', ['tenant_id'], unique=False)
    op.create_table('equipment_logs',
    sa.Column('dpr_id', sa.String(length=36), nullable=False),
    sa.Column('equipment_name', sa.String(length=255), nullable=False),
    sa.Column('equipment_code', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('WORKING', 'IDLE', 'BREAKDOWN', 'MAINTENANCE', name='equipmentstatus'), nullable=False),
    sa.Column('working_hours', sa.Float(), nullable=False),
    sa.Column('idle_hours', sa.Float(), nullable=False),
    sa.Column('fuel_consumed', sa.Float(), nullable=False),
    sa.Column('operator_name', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dpr_id'], ['daily_progress_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_logs_dpr_id'), 'equipment_logs', ['dpr_id'], unique=False)
    op.create_index(op.f('ix_equipment_logs_tenant_id'), 'equipment_logs', ['tenant_id'], unique=False)
    op.create_table('labour_attendance',
    sa.Column('dpr_id', sa.String(length=36), nullable=False),
    sa.Column('worker_name', sa.String(length=255), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=True),
    sa.Column('trade', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'HALF_DAY', 'ON_LEAVE', name='attendancestatus'), nullable=False),
    sa.Column('check_in', sa.String(length=10), nullable=True),
    sa.Column('check_out', sa.String(length=10), nullable=True),
    sa.Column('overtime_hours', sa.Float(), nullable=False),
    sa.Column('daily_wage', sa.Float(), nullable=False),
    sa.Column('is_subcontractor', sa.Boolean(), nullable=False),
    sa.Column('subcontractor_id', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dpr_id'], ['daily_progress_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labour_attendance_dpr_id'), 'labour_attendance', ['dpr_id'], unique=False)
    op.create_index(op.f('ix_labour_attendance_tenant_id'), 'labour_attendance', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_labour_attendance_tenant_id'), table_name='labour_attendance')
    op.drop_index(op.f('ix_labour_attendance_dpr_id'), table_name='labour_attendance')
    op.drop_table('labour_attendance')
    op.drop_index(op.f('ix_equipment_logs_tenant_id'), table_name='equipment_logs')
    op.drop_index(op.f('ix_equipment_logs_dpr_id'), table_name='equipment_logs')
    op.drop_table('equipment_logs')
    op.drop_index(op.f('ix_dpr_work_items_tenant_id'), table_name='dpr_work_items')
    op.drop_index(op.f('ix_dpr_work_items_dpr_id'), table_name='dpr_work_items')
    op.drop_table('dpr_work_items')
    op.drop_index(op.f('ix_daily_progress_reports_tenant_id'), table_name='daily_progress_reports')
    op.drop_index(op.f('ix_daily_progress_reports_site_id'), table_name='daily_progress_reports')
    op.drop_index(op.f('ix_daily_progress_reports_project_id'), table_name='daily_progress_reports')
    op.drop_table('daily_progress_reports')
    # ### end Alembic commands ###
